name: Pages

on:
  push:
    branches:
      - dev # default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: 查看
        run: |
          ls
          ls docs
          
